parameter_defaults:
  #
  # Glance Settings
  #
  GlanceEnabledImportMethods: web-download
  GlanceNfsEnabled: True
  GlanceNfsShare: 172.25.54.100:/lv_data/glance_images
  GlanceNodeStagingUri: file:///var/lib/glance/staging
  GlanceBackend: file

  # Disabled Options
  GlanceStagingNfsShare: ''
  NetappShareLocation: ''
  GlanceNetappNfsEnabled: False
  # END Disabled Options

  #
  # Cinder Settings
  #
  CinderBackupBackend: nfs
  CinderEnableNfsBackend: True
  CinderNfsServers: 172.25.54.100:/lv_data/cinder_volumes
  # Disabled Options
  CinderEnableIscsiBackend: False
  CinderEnableRbdBackend: False
  # END Disabled Options

  #
  # Nova Storage Settings
  #
  # These settings are false/disabled by default unless incorporating
  # their respective environment files. Defining the default value here
  # for readability
  # Disabled Options
  NovaNfsEnabled: False
  NovaEnableRbdBackend: false
  # END Disabled Options

